version: '3.7'

services:
  mongo:
    image: mongo:4.4
    container_name: mongodb
    volumes:
      - database:/data/db 
    ports:
      - 27017:27017
    networks:
      - app-network 

networks:
  app-network:
    external: true
    name: mnclabel

volumes: 
  database: