version: '3.7'

services:
  dbinit:
    build:
      context: .
      dockerfile: Dockerfile
    image: dbinit
    container_name: dbinit
    command: npm start
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 